import { newIdentifier } from "../../identifier";
import type { ComponentKind } from "../../types";
import type { GroupLink, SetupCatalog, SetupGroup } from "./setup-api";

export const COMPONENTS: ComponentKind[]=["lecture","laboratory","combined"];
export function TeachingMap({groups,links,faculty,title}:{groups:SetupGroup[];links:GroupLink[];faculty:SetupCatalog["faculty"];title:string}) {
  const lectures=groups.filter(g=>g.componentKind==="lecture");
  const unlinked=groups.filter(g=>g.componentKind!=="lecture" && !links.some(l=>l.laboratoryId===g.id));
  const label=(g:SetupGroup)=><><strong>{g.label||"Unnamed group"}</strong><small>{g.componentKind} · {g.facultyIds.map(id=>faculty.find(f=>f.id===id)?.displayName).filter(Boolean).join(", ")||"Instructor needed"}</small></>;
  return <aside className="teaching-map" aria-label="Teaching map"><h2>Teaching map</h2><p>{title}</p><ul>{lectures.map(g=><li key={g.id}>{label(g)}<ul>{links.filter(l=>l.lectureId===g.id).map(l=>{const lab=groups.find(x=>x.id===l.laboratoryId);return lab?<li key={lab.id}>{label(lab)}</li>:null;})}</ul></li>)}{unlinked.map(g=><li key={g.id}>{label(g)}</li>)}</ul><p className="setup-help">{groups.length} distinct groups. A lab shown under more than one lecture is the same group. Links do not enroll students or grant instructor access.</p></aside>;
}

export function TeachingGroups({groups,links,required,faculty,disabled,onChange,onLinks,onRequired}:{groups:SetupGroup[];links:GroupLink[];required:ComponentKind[];faculty:SetupCatalog["faculty"];disabled:boolean;onChange:(g:SetupGroup[])=>void;onLinks:(l:GroupLink[])=>void;onRequired:(k:ComponentKind[])=>void}) {
  const update=(id:string,change:Partial<SetupGroup>)=>onChange(groups.map(g=>g.id===id?{...g,...change}:g));
  return <fieldset disabled={disabled} className="setup-fields"><legend>Teaching groups</legend>
    <fieldset><legend>Required placement components</legend><p className="setup-help">Choose only components this offering requires. A combined group fulfills “combined”; lecture and laboratory require their explicitly selected groups.</p>{COMPONENTS.map(k=><label className="setup-check" key={k}><input type="checkbox" checked={required.includes(k)} onChange={e=>onRequired(e.target.checked?[...required,k]:required.filter(x=>x!==k))}/>{k}</label>)}</fieldset>
    {groups.map((g,index)=><fieldset className="setup-group-row" key={g.id}><legend>Group {index+1}</legend><div className="setup-form-grid"><label>Group label<input value={g.label} maxLength={80} onChange={e=>update(g.id,{label:e.target.value})}/></label><label>Component<select aria-label="Component" value={g.componentKind} onChange={e=>{update(g.id,{componentKind:e.target.value as ComponentKind});onLinks(links.filter(l=>l.lectureId!==g.id && l.laboratoryId!==g.id));}}>{COMPONENTS.map(k=><option key={k}>{k}</option>)}</select></label></div><fieldset><legend>Assigned instructors</legend>{faculty.map(f=><label className="setup-check" key={f.id}><input type="checkbox" checked={g.facultyIds.includes(f.id)} onChange={e=>update(g.id,{facultyIds:e.target.checked?[...g.facultyIds,f.id]:g.facultyIds.filter(x=>x!==f.id)})}/>{f.displayName}</label>)}</fieldset><button className="button button--small" onClick={()=>{onChange(groups.filter(x=>x.id!==g.id));onLinks(links.filter(l=>l.lectureId!==g.id && l.laboratoryId!==g.id));}}>Remove group</button></fieldset>)}
    <button className="button" onClick={()=>onChange([...groups,{id:newIdentifier(),label:"",componentKind:"laboratory",facultyIds:[]}])}>Add teaching group</button>
    <fieldset><legend>Optional lecture / laboratory associations</legend><p className="setup-help">Standalone groups are supported. Choose each relationship explicitly.</p>{links.map((l,i)=><div className="setup-link-row" key={i}><label>Lecture<select aria-label="Lecture" value={l.lectureId} onChange={e=>onLinks(links.map((x,n)=>n===i?{...x,lectureId:e.target.value}:x))}><option value="">Choose lecture</option>{groups.filter(g=>g.componentKind==="lecture").map(g=><option value={g.id} key={g.id}>{g.label}</option>)}</select></label><span aria-hidden="true">→</span><label>Laboratory<select aria-label="Laboratory" value={l.laboratoryId} onChange={e=>onLinks(links.map((x,n)=>n===i?{...x,laboratoryId:e.target.value}:x))}><option value="">Choose laboratory</option>{groups.filter(g=>g.componentKind==="laboratory").map(g=><option value={g.id} key={g.id}>{g.label}</option>)}</select></label><button className="button" onClick={()=>onLinks(links.filter((_,n)=>n!==i))}>Remove link {i+1}</button></div>)}<button className="button" onClick={()=>onLinks([...links,{lectureId:"",laboratoryId:""}])}>Add association</button></fieldset>
  </fieldset>;
}
